#!/bin/bash

TASK=$1
shift

case "$TASK" in
  build-dev)
    cargo build
    ;;
  build-release)
    cargo build --release
    ;;
  npm-build)
    cd ui && npm run build -- --mode debug
    ;;
  npm-build-release)
    cd ui && npm run build
    ;;
  npm-watch)
    cd ui && npm run build -- --mode debug --watch
    ;;
  "")
    cargo run
    ;;
  -v|-f)
    cargo run -- "$TASK" "$@"
    ;;
  -h|*)
    echo "Usage: ./run <command>
where command is one of:
    build-dev
    build-release
    npm-build
    npm-build-release
    npm-watch
    run [-v] [-f]"
    ;;
esac
